language: java

jdk: oraclejdk8

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_deploy:
  - gradle distZip
  - ls -R
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
   - "README.md"
   - "build/distributions/websocket-desktop-notifier-1.0.zip"
  skip_cleanup: true
  on:
    tags: true